<?xml version="1.0"?>
<package format="3">
  <name>ejercicio01_pubsub_py</name>
  <version>0.1.0</version>
  <description>Ejercicio 01 — publisher/subscriber en rclpy (Semana 01)</description>
  <maintainer email="ergrato-dev@example.com">bc-robotica</maintainer>
  <license>CC-BY-NC-SA-4.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
